-- MindMentor Database Schema
-- SQLite Database for JEE Exam Preparation System

-- User authentication and profiles
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    email TEXT,
    exam_target TEXT CHECK(exam_target IN ('JEE_MAIN', 'JEE_ADVANCED', 'BOTH')),
    daily_hours REAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    is_active BOOLEAN DEFAULT 1
);

-- Topics in the JEE syllabus (Physics, Chemistry, Mathematics)
CREATE TABLE IF NOT EXISTS topics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    subject TEXT NOT NULL CHECK(subject IN ('Physics', 'Chemistry', 'Mathematics')),
    chapter_name TEXT NOT NULL,
    topic_name TEXT NOT NULL,
    exam_weight REAL DEFAULT 1.0,
    difficulty_level TEXT CHECK(difficulty_level IN ('Easy', 'Medium', 'Hard')),
    prerequisites TEXT, -- JSON array of topic IDs
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(subject, chapter_name, topic_name)
);

-- LLM response cache (CRITICAL for API cost control)
CREATE TABLE IF NOT EXISTS llm_cache (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cache_key TEXT UNIQUE NOT NULL,
    model_used TEXT NOT NULL,
    prompt_template TEXT,
    response_content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_accessed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    access_count INTEGER DEFAULT 1,
    content_type TEXT -- 'lesson', 'question', 'explanation', 'grading'
);

-- Index for faster cache lookups
CREATE INDEX IF NOT EXISTS idx_llm_cache_key ON llm_cache(cache_key);
CREATE INDEX IF NOT EXISTS idx_llm_cache_accessed ON llm_cache(last_accessed);

-- Cached lesson content
CREATE TABLE IF NOT EXISTS lessons (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    topic_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    content_ref TEXT, -- reference to llm_cache.cache_key
    difficulty TEXT CHECK(difficulty IN ('Easy', 'Medium', 'Hard')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (topic_id) REFERENCES topics(id)
);

-- Questions for quizzes
CREATE TABLE IF NOT EXISTS questions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    topic_id INTEGER NOT NULL,
    question_type TEXT CHECK(question_type IN ('MCQ', 'NUMERIC', 'DESCRIPTIVE')),
    question_text TEXT NOT NULL,
    options TEXT, -- JSON array for MCQ
    correct_answer TEXT NOT NULL,
    explanation TEXT,
    difficulty TEXT CHECK(difficulty IN ('Easy', 'Medium', 'Hard')),
    content_ref TEXT, -- reference to llm_cache if generated by LLM
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (topic_id) REFERENCES topics(id)
);

-- Quiz sessions
CREATE TABLE IF NOT EXISTS quizzes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    quiz_type TEXT CHECK(quiz_type IN ('TOPIC', 'CHAPTER', 'MOCK_TEST')),
    topics TEXT, -- JSON array of topic IDs
    total_questions INTEGER,
    total_score REAL,
    obtained_score REAL,
    time_limit_minutes INTEGER,
    time_taken_minutes REAL,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Individual quiz attempts
CREATE TABLE IF NOT EXISTS attempts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    quiz_id INTEGER,
    topic_id INTEGER NOT NULL,
    question_id INTEGER NOT NULL,
    user_answer TEXT,
    correctness BOOLEAN,
    score REAL,
    time_taken_seconds REAL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id),
    FOREIGN KEY (topic_id) REFERENCES topics(id),
    FOREIGN KEY (question_id) REFERENCES questions(id)
);

-- Index for performance analytics
CREATE INDEX IF NOT EXISTS idx_attempts_user_topic ON attempts(user_id, topic_id);
CREATE INDEX IF NOT EXISTS idx_attempts_timestamp ON attempts(timestamp);

-- Study schedules
CREATE TABLE IF NOT EXISTS schedules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    date DATE NOT NULL,
    planned_items TEXT, -- JSON: [{"topic_id": 1, "activity_type": "learn", "duration_minutes": 60}]
    completed BOOLEAN DEFAULT 0,
    completion_percentage REAL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE(user_id, date)
);

-- Student learning profiles (tracks mastery per topic)
CREATE TABLE IF NOT EXISTS student_profiles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    topic_id INTEGER NOT NULL,
    mastery_score REAL DEFAULT 0.0 CHECK(mastery_score >= 0 AND mastery_score <= 1),
    last_attempt_date DATE,
    total_attempts INTEGER DEFAULT 0,
    correct_attempts INTEGER DEFAULT 0,
    accuracy REAL DEFAULT 0.0,
    avg_time_seconds REAL,
    revision_count INTEGER DEFAULT 0,
    next_review_date DATE,
    weak_concepts TEXT, -- JSON array of specific concepts
    strength_level TEXT CHECK(strength_level IN ('WEAK', 'AVERAGE', 'STRONG', 'MASTERED')),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (topic_id) REFERENCES topics(id),
    UNIQUE(user_id, topic_id)
);

-- Index for analytics queries
CREATE INDEX IF NOT EXISTS idx_student_profiles_user ON student_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_student_profiles_mastery ON student_profiles(user_id, mastery_score);

-- Chat history for conversational learning
CREATE TABLE IF NOT EXISTS chat_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    topic_id INTEGER,
    role TEXT CHECK(role IN ('user', 'assistant')),
    message TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (topic_id) REFERENCES topics(id)
);

-- Index for retrieving chat history
CREATE INDEX IF NOT EXISTS idx_chat_history_user_topic ON chat_history(user_id, topic_id, timestamp);

-- API usage tracking (to monitor costs)
CREATE TABLE IF NOT EXISTS api_usage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    model_used TEXT NOT NULL,
    operation_type TEXT, -- 'lesson_gen', 'question_gen', 'grading', etc.
    tokens_used INTEGER,
    cost_estimate REAL,
    cache_hit BOOLEAN DEFAULT 0,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Index for usage analytics
CREATE INDEX IF NOT EXISTS idx_api_usage_timestamp ON api_usage(timestamp);
CREATE INDEX IF NOT EXISTS idx_api_usage_user ON api_usage(user_id);
